# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: beta.gouv.fr - l'actualité
email: contact@beta.gouv.fr
description: L'actualité de l'incubateur de services publics numériques beta.gouv.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.beta.gouv.fr # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BetaGouv
github_username:  betagouv
github_repository: betagouv/blog.beta.gouv.fr


# Build settings
markdown: kramdown
# theme: jekyll-theme-gouvfr
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Options du template

lang: fr

include: ["_pages", "_category"]
exclude: ["content/templates"]

permalink: pretty

sass:
  style: compressed
  sass_dir: _sass

# Collections

collections_dir:
  content

collections:
  - newsletters
  - authors
  - incubators

defaults:
  - scope:
      path: "img/authors"
    values:
      authors_img: true
