version: '3'
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./_site:/app/_site
      - ./servers.conf.erb:/app/servers.conf.erb
      - ./ci/prepare-nginx-servers.conf.sh:/docker-entrypoint.d/40-prepare-servers.conf.sh
    environment:
      - PORT=80
    ports:
      - 8080:80
